/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  AbiItem,
  Callback,
  CeloTxObject,
  Contract,
  EventLog,
} from "@celo/connect";
import { EventEmitter } from "events";
import Web3 from "web3";
import { EventOptions } from "./types";

export interface ILendingPoolAddressesProviderV2 extends Contract {
  clone(): ILendingPoolAddressesProviderV2;
  methods: {
    getLendingPool(): CeloTxObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
export const ABI: AbiItem[] = [
  {
    inputs: [],
    name: "getLendingPool",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
];

export function newILendingPoolAddressesProviderV2(
  web3: Web3,
  address: string
): ILendingPoolAddressesProviderV2 {
  return new web3.eth.Contract(ABI, address) as any;
}
