/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  AbiItem,
  Callback,
  CeloTxObject,
  Contract,
  EventLog,
} from "@celo/connect";
import { EventEmitter } from "events";
import Web3 from "web3";
import { EventOptions } from "./types";

export interface ISwappaRouterV1 extends Contract {
  clone(): ISwappaRouterV1;
  methods: {
    getOutputAmount(
      path: string[],
      pairs: string[],
      extras: (string | number[])[],
      inputAmount: number | string
    ): CeloTxObject<string>;

    swapExactInputForOutput(
      path: string[],
      pairs: string[],
      extras: (string | number[])[],
      inputAmount: number | string,
      minOutputAmount: number | string,
      to: string,
      deadline: number | string
    ): CeloTxObject<string>;

    swapExactInputForOutputWithPrecheck(
      path: string[],
      pairs: string[],
      extras: (string | number[])[],
      inputAmount: number | string,
      minOutputAmount: number | string,
      to: string,
      deadline: number | string
    ): CeloTxObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
export const ABI: AbiItem[] = [
  {
    inputs: [
      { internalType: "address[]", name: "path", type: "address[]" },
      { internalType: "address[]", name: "pairs", type: "address[]" },
      { internalType: "bytes[]", name: "extras", type: "bytes[]" },
      { internalType: "uint256", name: "inputAmount", type: "uint256" },
    ],
    name: "getOutputAmount",
    outputs: [
      { internalType: "uint256", name: "outputAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address[]", name: "path", type: "address[]" },
      { internalType: "address[]", name: "pairs", type: "address[]" },
      { internalType: "bytes[]", name: "extras", type: "bytes[]" },
      { internalType: "uint256", name: "inputAmount", type: "uint256" },
      { internalType: "uint256", name: "minOutputAmount", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "swapExactInputForOutput",
    outputs: [
      { internalType: "uint256", name: "outputAmount", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address[]", name: "path", type: "address[]" },
      { internalType: "address[]", name: "pairs", type: "address[]" },
      { internalType: "bytes[]", name: "extras", type: "bytes[]" },
      { internalType: "uint256", name: "inputAmount", type: "uint256" },
      { internalType: "uint256", name: "minOutputAmount", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "swapExactInputForOutputWithPrecheck",
    outputs: [
      { internalType: "uint256", name: "outputAmount", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export function newISwappaRouterV1(
  web3: Web3,
  address: string
): ISwappaRouterV1 {
  return new web3.eth.Contract(ABI, address) as any;
}
