/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC20Contract } from "./ERC20";
import { IATokenContract } from "./IAToken";
import { IBPoolContract } from "./IBPool";
import { IBRegistryContract } from "./IBRegistry";
import { IERC20Contract } from "./IERC20";
import { IExchangeContract } from "./IExchange";
import { ILendingPoolContract } from "./ILendingPool";
import { ILendingPoolAddressesProviderContract } from "./ILendingPoolAddressesProvider";
import { ILendingPoolAddressesProviderV2Contract } from "./ILendingPoolAddressesProviderV2";
import { ILendingPoolV2Contract } from "./ILendingPoolV2";
import { IOpenSumSwapContract } from "./IOpenSumSwap";
import { ISavingsCELOContract } from "./ISavingsCELO";
import { ISwapContract } from "./ISwap";
import { ISwappaPairV1Contract } from "./ISwappaPairV1";
import { ISwappaRouterV1Contract } from "./ISwappaRouterV1";
import { ISymmetricSwapContract } from "./ISymmetricSwap";
import { IUniswapV2FactoryContract } from "./IUniswapV2Factory";
import { IUniswapV2PairContract } from "./IUniswapV2Pair";
import { PairATokenContract } from "./PairAToken";
import { PairATokenV2Contract } from "./PairATokenV2";
import { PairBPoolContract } from "./PairBPool";
import { PairMentoContract } from "./PairMento";
import { PairOpenSumSwapContract } from "./PairOpenSumSwap";
import { PairSavingsCELOContract } from "./PairSavingsCELO";
import { PairStableSwapContract } from "./PairStableSwap";
import { PairSymmetricSwapContract } from "./PairSymmetricSwap";
import { PairUniswapV2Contract } from "./PairUniswapV2";
import { SwappaRouterV1Contract } from "./SwappaRouterV1";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC20"): ERC20Contract;
      require(name: "IAToken"): IATokenContract;
      require(name: "IBPool"): IBPoolContract;
      require(name: "IBRegistry"): IBRegistryContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IExchange"): IExchangeContract;
      require(name: "ILendingPool"): ILendingPoolContract;
      require(
        name: "ILendingPoolAddressesProvider"
      ): ILendingPoolAddressesProviderContract;
      require(
        name: "ILendingPoolAddressesProviderV2"
      ): ILendingPoolAddressesProviderV2Contract;
      require(name: "ILendingPoolV2"): ILendingPoolV2Contract;
      require(name: "IOpenSumSwap"): IOpenSumSwapContract;
      require(name: "ISavingsCELO"): ISavingsCELOContract;
      require(name: "ISwap"): ISwapContract;
      require(name: "ISwappaPairV1"): ISwappaPairV1Contract;
      require(name: "ISwappaRouterV1"): ISwappaRouterV1Contract;
      require(name: "ISymmetricSwap"): ISymmetricSwapContract;
      require(name: "IUniswapV2Factory"): IUniswapV2FactoryContract;
      require(name: "IUniswapV2Pair"): IUniswapV2PairContract;
      require(name: "PairAToken"): PairATokenContract;
      require(name: "PairATokenV2"): PairATokenV2Contract;
      require(name: "PairBPool"): PairBPoolContract;
      require(name: "PairMento"): PairMentoContract;
      require(name: "PairOpenSumSwap"): PairOpenSumSwapContract;
      require(name: "PairSavingsCELO"): PairSavingsCELOContract;
      require(name: "PairStableSwap"): PairStableSwapContract;
      require(name: "PairSymmetricSwap"): PairSymmetricSwapContract;
      require(name: "PairUniswapV2"): PairUniswapV2Contract;
      require(name: "SwappaRouterV1"): SwappaRouterV1Contract;
    }
  }
}

export { ERC20Contract, ERC20Instance } from "./ERC20";
export { IATokenContract, IATokenInstance } from "./IAToken";
export { IBPoolContract, IBPoolInstance } from "./IBPool";
export { IBRegistryContract, IBRegistryInstance } from "./IBRegistry";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { IExchangeContract, IExchangeInstance } from "./IExchange";
export { ILendingPoolContract, ILendingPoolInstance } from "./ILendingPool";
export {
  ILendingPoolAddressesProviderContract,
  ILendingPoolAddressesProviderInstance,
} from "./ILendingPoolAddressesProvider";
export {
  ILendingPoolAddressesProviderV2Contract,
  ILendingPoolAddressesProviderV2Instance,
} from "./ILendingPoolAddressesProviderV2";
export {
  ILendingPoolV2Contract,
  ILendingPoolV2Instance,
} from "./ILendingPoolV2";
export { IOpenSumSwapContract, IOpenSumSwapInstance } from "./IOpenSumSwap";
export { ISavingsCELOContract, ISavingsCELOInstance } from "./ISavingsCELO";
export { ISwapContract, ISwapInstance } from "./ISwap";
export { ISwappaPairV1Contract, ISwappaPairV1Instance } from "./ISwappaPairV1";
export {
  ISwappaRouterV1Contract,
  ISwappaRouterV1Instance,
} from "./ISwappaRouterV1";
export {
  ISymmetricSwapContract,
  ISymmetricSwapInstance,
} from "./ISymmetricSwap";
export {
  IUniswapV2FactoryContract,
  IUniswapV2FactoryInstance,
} from "./IUniswapV2Factory";
export {
  IUniswapV2PairContract,
  IUniswapV2PairInstance,
} from "./IUniswapV2Pair";
export { PairATokenContract, PairATokenInstance } from "./PairAToken";
export { PairATokenV2Contract, PairATokenV2Instance } from "./PairATokenV2";
export { PairBPoolContract, PairBPoolInstance } from "./PairBPool";
export { PairMentoContract, PairMentoInstance } from "./PairMento";
export {
  PairOpenSumSwapContract,
  PairOpenSumSwapInstance,
} from "./PairOpenSumSwap";
export {
  PairSavingsCELOContract,
  PairSavingsCELOInstance,
} from "./PairSavingsCELO";
export {
  PairStableSwapContract,
  PairStableSwapInstance,
} from "./PairStableSwap";
export {
  PairSymmetricSwapContract,
  PairSymmetricSwapInstance,
} from "./PairSymmetricSwap";
export { PairUniswapV2Contract, PairUniswapV2Instance } from "./PairUniswapV2";
export {
  SwappaRouterV1Contract,
  SwappaRouterV1Instance,
} from "./SwappaRouterV1";
