/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ISwapContract extends Truffle.Contract<ISwapInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ISwapInstance>;
}

type AllEvents = never;

export interface ISwapInstance extends Truffle.ContractInstance {
  paused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  getToken(
    index: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  getBalances(txDetails?: Truffle.TransactionDetails): Promise<BN[]>;

  getSwapFee(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getAPrecise(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  swap: {
    (
      tokenIndexFrom: number | BN | string,
      tokenIndexTo: number | BN | string,
      dx: number | BN | string,
      minDy: number | BN | string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      tokenIndexFrom: number | BN | string,
      tokenIndexTo: number | BN | string,
      dx: number | BN | string,
      minDy: number | BN | string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      tokenIndexFrom: number | BN | string,
      tokenIndexTo: number | BN | string,
      dx: number | BN | string,
      minDy: number | BN | string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      tokenIndexFrom: number | BN | string,
      tokenIndexTo: number | BN | string,
      dx: number | BN | string,
      minDy: number | BN | string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  calculateSwap(
    tokenIndexFrom: number | BN | string,
    tokenIndexTo: number | BN | string,
    dx: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    paused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

    getToken(
      index: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    getBalances(txDetails?: Truffle.TransactionDetails): Promise<BN[]>;

    getSwapFee(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getAPrecise(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    swap: {
      (
        tokenIndexFrom: number | BN | string,
        tokenIndexTo: number | BN | string,
        dx: number | BN | string,
        minDy: number | BN | string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        tokenIndexFrom: number | BN | string,
        tokenIndexTo: number | BN | string,
        dx: number | BN | string,
        minDy: number | BN | string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        tokenIndexFrom: number | BN | string,
        tokenIndexTo: number | BN | string,
        dx: number | BN | string,
        minDy: number | BN | string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        tokenIndexFrom: number | BN | string,
        tokenIndexTo: number | BN | string,
        dx: number | BN | string,
        minDy: number | BN | string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    calculateSwap(
      tokenIndexFrom: number | BN | string,
      tokenIndexTo: number | BN | string,
      dx: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
